Build JavaScript files during python package build
posativ/isso pull request #697
Opened 2021-02-03 18:30 UTC by stefangehn

Make package builds via setuptools automatically trigger building of
merged & minified JS assets.

This fixes installing isso from source when using `pip install` as long
as both the python and node requirements are met. It also ensures that
`setup.py` commands like `build` or `bdist_wheel` create archives that
contain generated JS code.

2021-02-03 20:55 UTC, ix5 commented
That feels a bit too magic to me? Maybe just warn if the minified js files are not found.

2021-02-04 18:36 UTC, stefangehn commented
I wouldn't know what part should warn about these files missing.

Since this step is required for building a working redistributable package (may it be a wheel or just a tarball) this looks like a good place to me. It also makes it obvious that you will need npm if you use `pip install` on the github URL instead of failing more or less silently in the browser because the required files are missing.

The idea for this was actually taken from the readthedocs sphinx theme:
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/setup.py#L16

2021-02-04 20:32 UTC, ix5 commented
Again, just my personal preference. I can see that your approach would solve a lot of annoying newbie issues.

The primary reason for people to install from source is because the isso package in pypi has historically been outdated or even broken (`werkzeug==1.0`) for long stretches of time.

People installing directly via `pip install git+https://github.com/posativ/isso` would need to have node+npm installed already, which might be non-obvious. I'd also wager that these people don't really want to install all this js ecosystem stuff just to get an updated package.

My favourite way to resolve this whole issue would be to keep minified versions of the js assets in this repo, but sadly that might break the `make`-based change detection.

---

(I guess your approach wouldn't affect FTBFS issues since you'd invoke the make commands in the "prepare" stage anyway, and not use python to generate the minified js assets?)

2021-02-05 11:27 UTC, ix5 commented
I've created https://github.com/posativ/isso/pull/703 to clarify more issues that might pop up when installing from source.
But I'm growing more and more partial to your approach, considering e.g. the experience of users in https://github.com/posativ/isso/issues/656.

2021-02-07 20:46 UTC, jelmer approved these changes

2021-04-19 17:29 UTC, stefangehn commented on setup.py
> +            subprocess.run(['make', 'init', 'js'], check=True)
Indeed. Although `subprocess.run(..., check=True)` does the same I find `subprocess.check_call()` to be a bit more obvious and in fact know it from Python 2.7 already.

2021-04-19 17:30 UTC, stefangehn commented
Rebased and applied the `check_call()` suggestion.

Sorry for the long delay, work and health kept me busy lately.

2021-12-22 14:07 UTC, jelmer requested changes
Please resolve the conflict?

2022-01-04 19:29 UTC, merged

2022-02-13 23:20 UTC, ix5 commented
Note that packages created by `python3 setup.py sdist` and installed via pip will attempt to run the `NpmBuildCommand`.
A way to specify that the command is only to be run when installing from source is needed.

2022-02-16 20:39 UTC, stefangehn commented
Feel free to revert, I don't need it myself and I don't intend to dive any further into the sorry state of python packaging

2022-02-16 20:59 UTC, jelmer commented
Let's revert.