setup.py: drop python3.5 support
posativ/isso pull request #808
Opened 2022-03-06 14:09 UTC by fliiiix

Since not tests are run for 3.5 drop support
with the next release.
Also Python 3.5 has reached end-of-life on 5-Sep-2020.
Python 3.5.10 is the final release of 3.5.
https://www.python.org/downloads/release/python-3510/

2022-03-06 14:10 UTC, fliiiix commented
Technically even 3.6 is unsupported but as long as there is no need to drop support i would argue its continent to still support it.

2022-03-06 14:12 UTC, fliiiix commented
This change should probably be noted in some changelog?

2022-03-15 16:50 UTC, ix5 requested changes
Please also change `docs/docs/install.rst` which mentions 3.5 as well

2022-03-15 16:50 UTC, ix5 commented on CHANGES.rst
> +- Drop support for outdate Python version 3.5
outdated

2022-03-15 16:52 UTC, ix5 commented
Hey @fliiiix, you're also very welcome to join the `#isso` IRC channel, preferably via [Matrix: #isso](https://matrix.to/#/#isso:libera.chat) or on [Libera.Chat](https://libera.chat/) directly.

2022-03-16 12:07 UTC, fliiiix commented
I will update this PR hopefully on the weekend.

2022-03-21 20:28 UTC, ix5 commented
While you're at it, maybe also test compatibility with 3.11 and advertise that?

2022-03-27 17:44 UTC, fliiiix commented on CHANGES.rst
> +- Drop support for outdate Python version 3.5
done

2022-03-27 17:44 UTC, fliiiix commented
3.11 is not release yet so i would wait for the official release

2022-03-27 21:45 UTC, merged

2022-03-27 21:48 UTC, ix5 commented
> 3.11 is not release yet so i would wait for the official release

My thinking was that we can already put it into the GH actions test matrix before the release is out, but not yet adversise support in `setup.py`.

Doesn't matter too much though, merged.