github-action: tests agains 3.11.0-alpha.6
posativ/isso pull request #832
Opened 2022-03-28 08:22 UTC by fliiiix

2022-10-29 09:19 UTC, fliiiix commented
It might make sense to also upgrade the [Dockerfile](https://github.com/posativ/isso/blob/master/Dockerfile#L29) but i could not tst that so its not included 

```
 => ERROR [isso-builder  3/11] RUN python3 -m venv /isso  && . /isso/bin/activate  && pip3 install --no-cache-dir --upgrade pip  && pip3 install --no-cache-dir gu  0.5s
```

and update the docs build 
https://github.com/posativ/isso/blob/master/.github/workflows/build-upload-docs.yml#L27

same issue here no idea how to test so i did not upgrade it

But I think this PR is ready to go

2022-10-30 19:31 UTC, ix5 commented
Time indeed moves fast... Totally forgot about this. Would you mind pinging me about this on Wednesday?

2022-11-02 11:45 UTC, fliiiix commented
ping

2022-11-02 12:46 UTC, ix5 commented
Please amend the slight wording suggestion, and create a separate commit for the `setup.py` change.

Otherwise LGTM

2022-11-02 12:46 UTC, ix5 requested changes

2022-11-02 12:46 UTC, ix5 commented on CHANGES.rst
> +- Test Python 3.11 support (`#832`_, l33tname)
Simply "Python 3.11 support"

2022-11-03 11:45 UTC, fliiiix commented
I think i addressed all the feedback let me know if there is something else missing to get this merged

2022-11-03 14:39 UTC, merged

2022-11-03 14:40 UTC, ix5 commented
Thanks your your contribution and patience!